name: Check JIRA Ticket Consumer

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title matches JIRA
        uses: pauta-eletronica/workflows/.github/workflows/reusable-workflow.yml@master
        with:
          jira_base_url: ${{ secrets.JIRA_BASE_URL }}
          jira_email: ${{ secrets.JIRA_EMAIL }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
